# fly.toml app configuration file generated for connect-site on 2024-04-16T20:20:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'connect-site'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[http_service]
  internal_port = 3000

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256MB'
  processes = ['app']
